# The driver of the dual deserializer.
# It also setups the 9295D deserializer.
obj-$(CONFIG_SL_DESER_MAX9296) += max9296/

# The driver of the quad deserializer.
# It also setups the 9295D serializer.
obj-$(CONFIG_SL_DESER_MAX96712) += max96712/

# The driver of the ZED-X camera.
obj-$(CONFIG_SL_VIDEO_ZEDX) += zedx/

# Just if necessary
# ccflags-y += -I$(src)/../../include
